### ISSUE TITLE
Donating Funds to Solidity-Parser

### ISSUE THREAD

**Issue by Lfada** [solidity-parser/parser#114]
Hi Solidity Parser maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

The [Hardhat Gas Reporter](https://github.com/cgewecke/hardhat-gas-reporter) and [Solidity Coverage](https://github.com/sc-forks/solidity-coverage) maintainers have been using https://github.com/solidity-parser/parser. It's in fact one of their most critical dependencies!

Hardhat Gas Reporter core contributors appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/).

Who can I talk to about it?

cc: @fvictorio , @federicobond @Janther

**Comment by Janther** [comment]
Thank you @Lfada.
Already configured this on drips :smile:

**Comment by Lfada** [comment]
Amazing! thank you for doing that @Janther 

Would you share some feedback with us (what you loved, what can be improved) and NPS score (1 shit, 10 amazing)
