### ISSUE TITLE
Reference to ctx.constructor.name in ASTBuilder breaks webpack production builds

### ISSUE THREAD

**Issue by Pet3ris** [solidity-parser/parser#21]
Hi There,

I'm running into an issue where a simple `parse` on the following contract code results in divergent parsing locally vs. in production (javascript):

```
// Extremely simple Solidity contract example.
import "File1";

pragma solidity >=0.6.7;

contract Test is Test2 {
	uint z = 0;

	function test() public returns (uint256) {
		other();
		y += 1;
		z += 1;
	}
}
```

Locally I get an AST element starting with `SourceUnit`, in production I get an object like so:

```
[
  {
    "type": "p"
  }
]
```

Do you have any thoughts on what may be causing this? Is there perhaps an `antlr` compilation step that occurs as the `yarn` package is installed?

**UPDATE**: For more details, see below, but effectively the key problem is this reference: https://github.com/solidity-parser/parser/blob/master/src/ASTBuilder.js#L1458. Classes get renamed during webpack optimisation so references to class names are not supported. This could be fixed by manually adding a type property to each class rather than automatically deriving it from the class name.

**Comment by Pet3ris** [comment]
**Update**: The difference arises from use of `webpack`.

With `NODE_ENV=production webpack`, there are issues, without there aren't issues. Currently investigating whether certain essential code may get optimised away.

**Comment by Pet3ris** [comment]
I've now reproduced this issue in a minimal repository where you can run it with:

1) `npm run start` => to see how it runs successfully (observe `console.log` output)
2) `npm run preview` => to see how it fails in production (observe `console.log` output)

**Comment by Pet3ris** [comment]
*UPDATE* - the issue is the reference to construtor names, more from `webpack` authors here: https://github.com/webpack/webpack/issues/11174#issuecomment-658306109.

**Comment by Pet3ris** [comment]
Current workaround: add this to your `webpack.prod.js` (production config):

```javascript
  optimization: { // Fix for https://github.com/solidity-parser/parser/issues/21
    minimize: true,
    minimizer: [
        new TerserPlugin({
          terserOptions: {
            keep_fnames: /(SourceUnit|UsingForDeclaration|PragmaDirective|ContractDefinition|InheritanceSpecifier|FunctionDefinition|TypeName|FunctionTypeName|EmitStatement|FunctionCall|IfStatement|TryStatement|CatchClause|UserDefinedTypeName|Block|NumberLiteral|Mapping|ModifierDefinition|Expression|StateVariableDeclaration|ForStatement|ImportDirective|EventDefinition|InlineAssemblyStatement|AssemblyCall)/,
          },
        }),
    ]
  }
```

**Comment by fvictorio** [comment]
Hey @Pet3ris, thanks a lot for this!

For some reason, my GitHub user stopped watching this repo and I missed a couple of issues :/ Sorry about that. I'll look into this as soon as I can.

**Comment by Pet3ris** [comment]
No problem @fvictorio - I didn't know webpack made assumptions about code structure so this was interesting.

**Comment by fvictorio** [comment]
Hey @Pet3ris, now I understand your issue: the problem is when you consume this module from a project that uses webpack and minimizes the code, right?

I don't think there's a workwaround for this :( The `Context` suffix thing comes from [antlr](https://www.antlr.org/), so it's not something I can control. The only thing I can do is add a section in the README with a warning about this.

**Comment by Pet3ris** [comment]
@fvictorio - that makes sense! Hopefully the work-around is useful for other people running into this issue.

I suspect that this hasn't been an issue so far because most have used solidity parser in the back-end, where people don't tend to use webpack as much.
