### ISSUE TITLE
Add support for parsing the SPDX-License-Identifier

### ISSUE THREAD

**Issue by sebastinez** [solidity-parser/parser#22]
Solidity 0.6.8 introduces SPDX license identifiers so developers can specify the license the contract uses. [Source](https://github.com/ethereum/solidity/releases/tag/v0.6.8)

I think there are tools that use this library that would benefit if this would be implemented for example solhint.

I would like to provide a PR to implement this, but I'm a little bit out of my depth here.. If one can give me a hint how to implement an additional type with the mentioned formatting, would greatly appreciate it.

**Comment by sebastinez** [comment]
I opened a [PR](https://github.com/solidity-parser/antlr/pull/7) on the antlr repo with support for the `// SPDX-License-Identifier`.

But I encountered conflicts with the regular comment keyword
```
LINE_COMMENT
  : '//' ~[\r\n]* -> channel(HIDDEN)
```
If anyone could help out, would really appreciate it.

**Comment by fvictorio** [comment]
Hey @sebastinez, I totally missed this issue and the PR! Sorry about that.

Right now the parser just ignores all comments, which is a shame for things like this or natspec. I don't really know the best way to do this, but I'll try to do some research. Thanks for opening this issue!

**Comment by sebastinez** [comment]
One way I resolved the issue of the comment ignoring is by adding the comments to the AST.

For example for the spdx-license:
```g4

spdx-license:
  : LINE_COMMENT 'SPDX-License-Identifier:' identifier ;

general-comment:
  : LINE_COMMENT identifier* ;

LINE_COMMENT
  : '//' ~[\r\n]* ;
```

The problem with this approach is that one has to implement the comment token in every place where comments can occur, which is almost everywhere..

The other approach but would be to send comments to a separate channel and filter/search them in the wrapper instead of antlr. But I haven't found a way to receive them in the solhint wrapper.

Will investigate more, if I find a way, but I think it would be best to delegate the issue to the wrapper..

**Comment by fvictorio** [comment]
Yeah, this is tricky, and I'm not proficient enough in antlr to know the best way to do this :( But this is something with a lot of potential (it could also be used to detect natspec comments), so I'll leave this open in case anyone knows better, or until I have enough time to give it a deep dive.

**Comment by naddison36** [comment]
Does anyone know of a way to parse Natspec without using the solc compiler?

I'd like to add a feature to sol2uml that outputs contract doco but I see the Solidity parser doesn't currently support parsing comments. Using solc in sol2uml is not ideal as it pulls contract source from Etherscan which can be any Solidity version. I'd like to avoid downloading the matching solc version just to parse Natspec.

Thanks
