### ISSUE TITLE
Support gwei as a literal unit

### ISSUE THREAD

**Issue by adhusson** [solidity-parser/parser#37]
Currently, the parser only supports `wei`, `szabo`, `finney`, `ether` as well as time units. But while solc doesn't support `szabo` nor `finney` [since 0.7.0](https://github.com/ethereum/solidity/blob/develop/Changelog.md#070-2020-07-28), it supports `gwei` [since 0.6.11](https://github.com/ethereum/solidity/blob/develop/Changelog.md#0611-2020-07-07).

**Comment by fvictorio** [comment]
Thank you @adhusson, I'll take care of this next week.

**Comment by fvictorio** [comment]
Fixed in `v0.11.1`.
