### ISSUE TITLE
Some interfaces are incorrectly typed in `ast-types.d.ts`

### ISSUE THREAD

**Issue by lonelyenvoy** [solidity-parser/parser#40]
Thank you for implementing the parser - it's very useful.

I'd like to point out some typing problems in `dist/ast-types.d.ts`.

### The type of `BaseASTNode.loc` is wrong
```typescript
export interface BaseASTNode {
    type: ASTNodeTypeString;
    range?: [number, number];
    loc?: Location;
}
```

I guess the definition of `Location` is missing? The `Location` here is an interface in the [typescript standard library](https://github.com/microsoft/TypeScript/blob/df5ffc0ea11712d80fb0d1ee2fa5607715ac0b1e/lib/lib.dom.d.ts#L9794) and has nothing to do with line of code.

### The type of `ASTNodeTypeString` is unsound
```typescript

export declare type ASTNodeTypeString = 'SourceUnit' | 'PragmaDirective' | 'PragmaName' | 'PragmaValue' | 'ImportDirective' | 'ContractDefinition' | 'InheritanceSpecifier' | 'StateVariableDeclaration' | 'UsingForDeclaration' | 'StructDefinition' | 'ModifierDefinition' | 'ModifierInvocation' | 'FunctionDefinition' | 'EventDefinition' | 'EnumValue' | 'EnumDefinition' | 'VariableDeclaration' | 'UserDefinedTypeName' | 'Mapping' | 'ArrayTypeName' | 'FunctionTypeName' | 'StorageLocation' | 'StateMutability' | 'Block' | 'ExpressionStatement' | 'IfStatement' | 'WhileStatement' | 'ForStatement' | 'InlineAssemblyStatement' | 'DoWhileStatement' | 'ContinueStatement' | 'Break' | 'Continue' | 'BreakStatement' | 'ReturnStatement' | 'EmitStatement' | 'ThrowStatement' | 'VariableDeclarationStatement' | 'IdentifierList' | 'ElementaryTypeName' | 'FunctionCall' | 'AssemblyBlock' | 'AssemblyItem' | 'AssemblyCall' | 'AssemblyLocalDefinition' | 'AssemblyAssignment' | 'AssemblyStackAssignment' | 'LabelDefinition' | 'AssemblySwitch' | 'AssemblyCase' | 'AssemblyFunctionDefinition' | 'AssemblyFunctionReturns' | 'AssemblyFor' | 'AssemblyIf' | 'AssemblyLiteral' | 'SubAssembly' | 'TupleExpression' | 'TypeNameExpression' | 'NameValueExpression' | 'BooleanLiteral' | 'NumberLiteral' | 'Identifier' | 'BinaryOperation' | 'UnaryOperation' | 'NewExpression' | 'Conditional' | 'StringLiteral' | 'HexLiteral' | 'HexNumber' | 'DecimalNumber' | 'MemberAccess' | 'IndexAccess' | 'IndexRangeAccess' | 'NameValueList' | 'UncheckedStatement';
```
Some node types are missing in this declaration, e.g. `'TryStatement'` and `'FileLevelConstant'`.

### Interfaces of some AST node types derived from `BaseASTNode` are not given

```typescript
export interface SourceUnit extends BaseASTNode {
    type: 'SourceUnit';
    children: ASTNode[];
}
```
The interface like this is very useful, but some are missing, e.g. `PragmaName`, `PragmaValue`, `StorageLocation`, `StateMutability`, and `IdentifierList`.

**Comment by fvictorio** [comment]
Yeah, I tried to improve this but it's still a mess. I want to at some point make things so that the project doesn't compile if the node types are not correct. Sadly I haven't been able to do it yet.

**Comment by fvictorio** [comment]
I think this is no longer relevant, since the project uses typescript now.
