### ISSUE TITLE
ArrayTypeName.length incorrect type

### ISSUE THREAD

**Issue by naddison36** [solidity-parser/parser#52]
`ArrayTypeName` is currently defined with `length` having type `Expression | null`
```ts
export interface ArrayTypeName extends BaseASTNode {
  type: 'ArrayTypeName'
  baseTypeName: TypeName
  length: Expression | null
}
```

At runtime, the length for a fixed length array is returning a `length` of type `NumberLiteral`. So the type should be
```ts
export interface ArrayTypeName extends BaseASTNode {
  type: 'ArrayTypeName'
  baseTypeName: TypeName
  length: NumberLiteral | null
}
```

Some example fixed length arrays are
```
bool[2] flags = [true, false];
uint256[2][3] multiDim2x3;
address[3][2] multiDim3x2;
```

I tried to create a PR for this but I got lost in the required ASTBuilder changes in the `visitTypeName` function.

**Comment by fvictorio** [comment]
Hey @naddison36, I'm not sure this is correct. It's possible to use something that is not a `NumberLiteral` there. An obvious case is:

```solidity
uint[3 + 3] x;
```

and a more realistic one is:

```solidity

contract Foo {
  uint constant length = 3;

  function f() public {
    uint[length] memory x;
  }
}
```

Please re-open if I'm missing something here!
