### ISSUE TITLE
VariableDeclaration type missing isImmutable

### ISSUE THREAD

**Issue by naddison36** [solidity-parser/parser#53]
The `VariableDeclaration` type is missing the `isImmutable` boolean value which is available at runtime

```ts
export interface VariableDeclaration extends BaseASTNode {
  type: 'VariableDeclaration'
  isIndexed: boolean
  isStateVar: boolean
  typeName: TypeName | null
  name: string | null
  identifier: Identifier | null
  isDeclaredConst?: boolean
  storageLocation: string | null
  expression: Expression | null
  visibility?: 'public' | 'private' | 'internal' | 'default'
}```

**Comment by fvictorio** [comment]
The `isImmutable` field is present in the `StateVariableDeclarationVariable` type, which is a sub-type of `VariableDeclaration` (there are variable declarations that cannot have the immutable keyword).

I know the types are a bit of a mess, sorry! If you think this can be improved in a backards-compatible way, let me know.
