### ISSUE TITLE
Cannot parse `pragma solidity *;`

### ISSUE THREAD

**Issue by fvictorio** [solidity-parser/parser#55]

**Comment by ControlCplusControlV** [comment]
Need any help on this? Would love to help out for hacktoberfest!

**Comment by sambacha** [comment]
:))))))))))


looking forward to the next release!

**Comment by fvictorio** [comment]
Hey @sambacha, I already released this but under the `beta` tag, because I did several changes in one go and I want to be sure I didn't break anything. You should be able to try it out with `npm i @solidity-parser/parser@beta`.

**Comment by sambacha** [comment]
Awesome! FYI i just updated the PR against hardhat repo just now.

Will be testing it out with the updated prettier build today thx.


Also Antlr has redone their javascript runtime in the latest release may be worth considering an update from the current version idk 🤷‍♂️ 

Cheers
