### ISSUE TITLE
[Question] How can I re-generate solidity source code after I make changes to the AST?

### ISSUE THREAD

**Issue by Troublor** [solidity-parser/parser#62]
Hi, I would like to transpile solidity source code by first generating AST from source code, modifying AST, and then generating source code based on the modified AST. Is this possible with `solidity-parser`? I can only find `parse` API in the documentation.

**Comment by fvictorio** [comment]
Hey @Troublor, sorry for not responding before. This is not possible with the parser, but it might be possible with the prettier API. I'm not 100% sure about this, though. There was some issue about adding a function that receives an AST directly, but I don't know if that's already available.

**Comment by fvictorio** [comment]
I believe you should do something like [this](https://gist.github.com/donaldpipowitch/222b673fc3af4aee5a797920099b7ddd). I haven't tried it, but the approach looks correct: you run prettier (with the solidity plugin included) using a custom parser that runs this parser, makes some modifications to the AST, and returns the modified AST.

Sorry for not being able to give you more specific tips, but if you have any other questions I would be glad to help.

**Comment by Troublor** [comment]
Yes, it is possible with [prettier-solidity-plugin](https://github.com/prettier-solidity/prettier-plugin-solidity). However, it is not an easy use.

Just as you mentioned, I had to create a [custom prettier plugin](https://prettier.io/docs/en/plugins.html#developing-plugins) by extending the existing [prettier-solidity-plugin](https://github.com/prettier-solidity/prettier-plugin-solidity). 
Then I implement my logic of AST mutation as a custom parser of prettier and pass the mutated AST to printer of [prettier-solidity-plugin](https://github.com/prettier-solidity/prettier-plugin-solidity). 
It works for me.

**Comment by Troublor** [comment]
For those who come later. Another choice is to use [solc-typed-ast](https://github.com/ConsenSys/solc-typed-ast), which provides APIs to do this. However, the AST structure there may be different from this library.
