### ISSUE TITLE
Add support for "user defined operators"

### ISSUE THREAD

**Issue by Amxx** [solidity-parser/parser#80]
Solidity 0.8.19 introduced operator for UDVT using the syntax

```solidity
using { f as + } for S global;
```

However, this is not supported by the current parser:

```javascript
parseNode('using { f as + } for S global;')
```
```
Error: mismatched input 'as' expecting {',', '}'} (1:26)
```

**Comment by Amxx** [comment]
This should probably get in first: https://github.com/solidity-parser/antlr/pull/17/files

**Comment by Amxx** [comment]
Alternatively, this one should be used instead:
https://github.com/ethereum/solidity/blob/develop/docs/grammar/SolidityParser.g4

**Comment by fvictorio** [comment]
Fixed in the latest version.



> Alternatively, this one should be used instead: https://github.com/ethereum/solidity/blob/develop/docs/grammar/SolidityParser.g4

I think you know this now, but just in case: that grammar is not compatible with previous versions of Solidity. The one used by this plugin has to parse basically all solidity versions, and does that by being super permissive. It's not ideal, but it kind of works.
