### ISSUE TITLE
Cannot bundle for Node without forging `BROWSER`

### ISSUE THREAD

**Issue by llllvvuu** [solidity-parser/parser#89]
If you look at the `esbuild` output: 

```javascript
// src/tokens-string.js
var require_tokens_string = __commonJS((exports, module2) => {
  if (typeof BROWSER !== "undefined") {
    module2.exports = require_Solidity();
  } else {
    module2.exports = require("fs").readFileSync(require("path").join(__dirname, "./antlr/Solidity.tokens")).toString();
  }
});
```

If I consume this in a downstream package, my bundler (e.g. `esbuild`, `rollup`, `webpack`) won't bundle `./antlr/Solidity.tokens` since it is `readFileSync`ed, not `require`d (even if it did, it'd be bundled under a different path/name). This will cause `node ./bundle.js` to fail. Forging `BROWSER` fixes this specific package, but it doesn't seem ideal since we're still using it in `node`; it might also break other packages.

One might ask, why bundle for `node` runtime? The reason is I'm bundling a VSCode extension.

My question is, why not:
```diff
- if (typeof BROWSER !== "undefined") {
-   module.exports = require('./antlr/Solidity.tokens')
- } else {
-   module.exports = require('fs')
-     .readFileSync(require('path').join(__dirname, './antlr/Solidity.tokens'))
-     .toString()
- }
+ module.exports = require('./antlr/Solidity.tokens')
```

**Comment by Janther** [comment]
The parser doesn't read the file from the OS anymore
