### ISSUE TITLE
CustomErrorDefinition as nodeType for errors

### ISSUE THREAD

**Issue by vladyan18** [solidity-parser/parser#93]
It looks like solc is using "ErrorDefinition" as the node type for errors: https://github.com/ethereum/solidity/blob/df03f1412d43e1756881d8f8c7b8bd7a77d61637/libsolidity/ast/ASTJsonExporter.cpp#L585

But this tool uses "CustomErrorDefinition":
https://github.com/solidity-parser/parser/blob/a3228b58f08f9ba4617189a1741752a4c268712d/src/ASTBuilder.ts#L750

This difference can create inconvenience and interfere with integration of the tool into other packages. I think it's better to go with "ErrorDefinition" unless there is some special reason not to. On the other hand, it could be breaking change.

**Comment by fvictorio** [comment]
I'm pretty sure this is a breaking change, so I wouldn't do it unless there is a really good reason to.

I try to follow the terminology that solc uses, but there's no guarantee that it will be the same. Plus, solc's antlr definitions are per versions and can change, while this one has to remain stable.

Tentatively closing, happy to answer any questions or re-consider if there is a good reason to do this.
