### ISSUE TITLE
Support for Solidity 0.8.22 

### ISSUE THREAD

**Issue by Janther** [solidity-parser/parser#96]
Solidity 0.8.22 allowed event definitions at file level.

https://soliditylang.org/blog/2023/10/25/solidity-0.8.22-release-announcement/

**Comment by Janther** [comment]
Also now we can emit events from different contexts so `EmitStatement` must support `MemberAccess` as well.

```Solidity
interface I {
    event ForeignEvent();
}

contract C {
    event ForeignEvent();
}

event E();

contract D {
    function f() public {
        // Emitting a foreign event would trigger an internal error on 0.8.21
        emit I.ForeignEvent();
        emit C.ForeignEvent();
        
        // Emitting a file-level event. New feature.
        emit E();
    }
}
```

**Comment by jeasonstudio** [comment]
I use solidity official antlr4-grammer to implement a more comprehensive ast parser. You can consider giving it a try:
https://github.com/jeasonstudio/solidity-antlr4

**Comment by fvictorio** [comment]
The difference between this project and the official grammar is that this parser supports "all" solidity versions. That is, it supports a weird superset of the language, which is necessary for a lot of projects (e.g., prettier-solidity). But I'm glad to see a parser generated by the official one!

**Comment by jeasonstudio** [comment]
> The difference between this project and the official grammar is that this parser supports "all" solidity versions. That is, it supports a weird superset of the language, which is necessary for a lot of projects (e.g., prettier-solidity). But I'm glad to see a parser generated by the official one!

Thanks for your awesome project, I understand what you means, it's not easy to support the syntax of all versions of Solidity. As Solidity becoming more stable, it might be a better choice to align the versions of the parser and Solidity grammar one by one. : )

**Comment by fvictorio** [comment]
My hope is that that will be provided by [Slang](https://github.com/NomicFoundation/slang) soon enough.
